name = "TreeTransform"
uuid = "d236873b-e432-4afc-a13d-4d3ddb9f1c9d"
authors = ["Neal Gafter <neal@gafter.com> and contributors"]
version = "0.0.1"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Rematch2 = "351a7294-9038-49b6-b9cf-e076b05af63f"

[compat]
OrderedCollections = "1"
julia = "1.6.2"

[targets]
test = ["Rematch2"]
