name = "TreeTransform"
uuid = "d236873b-e432-4afc-a13d-4d3ddb9f1c9d"
authors = ["Neal Gafter <neal@gafter.com> and contributors"]
version = "0.0.1"

[deps]
Rematch2 = "351a7294-9038-49b6-b9cf-e076b05af63f"

[compat]
julia = "1.5"

[extras]

[targets]
test = ["Rematch2"]
